# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sblog', '0002_auto_20160928_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sblog.Author', verbose_name='\u4f5c\u8005'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, to='sblog.Tag', verbose_name='\u6807\u7b7e'),
        ),
    ]
