# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sblog', '0003_auto_20160928_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u6807\u7b7e'),
        ),
    ]
